apiVersion: v1
data:
  admin.enabled: 'true'
  statusbadge.enabled: 'false'
  users.anonymous.enabled: 'false'
  url: https://cd.test.ai
  configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build"]
        generate:
          command: [sh, -c]
          args: ["helm template . > all.yaml && kustomize build"]
kind: ConfigMap
metadata:
  name: argocd-cm