apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    slack:
      enabled: true
      token: xoxb-1276078135890-1276084368770-zbvE0ppEgoEgiAAMtQvhE5cg
type: Opaque