apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    slack:
      enabled: true
      token: xoxb-1276078135890-1276084368770-T9cS3zONIz6ZTtypHU43OJM6
type: Opaque